### ISSUE TITLE
Error with command: npm start

### ISSUE THREAD

**Issue by mohamedmehdigara** [bouncei/scandi-web-test#1]
Failed to compile
C:/Users/p-c/Downloads/Github/scandi-web-test/src/index.tsx
Type error: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Element | DocumentFragment'.
  Type 'null' is not assignable to type 'Element | DocumentFragment'.  TS2345
<pre>
   import store from './Redux/store';
    11 | 
  > 12 | const root = ReactDOM.createRoot(document.getElementById('root'));
       |                                  ^
    13 | root.render(
    14 |   <React.StrictMode>
    15 |     <ApolloProvider client={client}>
</pre>
This error occurred during the build time and cannot be dismissed.

**Comment by bouncei** [comment]
Thanks for the observation. You can fix that failed to compile error by renaming the file from "index.tsx" to "index.js"
